[build-system]
requires = ["setuptools>=80", "setuptools-scm[simple]>=9.2", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyspssio"
description = "Read and write SPSS (.sav and .zsav) files to/from pandas dataframes"
authors = [{ name = "Steven Spector", email = "stspec.dev@gmail.com" }]
license = "MIT"
license-files = ["LICENSE.txt"]
requires-python = ">=3.6"
dependencies = ["pandas", "psutil"]
dynamic = ["version"]

[dependency-groups]
dev = ["pytest", "pytest-order", "wheel", "cibuildwheel"]

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.urls]
Homepage = "https://github.com/stspec/pyspssio"
Documentation = "https://pyspssio.readthedocs.io"

[project.scripts]
pyspssio = "pyspssio.command_line:main"

[tool.setuptools]
packages = ["pyspssio"]

[tool.cibuildwheel]
build = "cp314-*"
skip = "cp314t-*"

[tool.cibuildwheel.windows]
archs = ["AMD64"]
environment = "SPSSIO_PLATFORM_DIR=win64"

[tool.cibuildwheel.macos]
archs = ["x86_64"]
environment = "SPSSIO_PLATFORM_DIR=macos"
repair-wheel-command = [
    "delocate-wheel --ignore-missing-dependencies -w {dest_dir} {wheel}",
]

[tool.cibuildwheel.linux]
archs = ["x86_64"]
environment = "SPSSIO_PLATFORM_DIR=lin64"
repair-wheel-command = [
    "auditwheel repair --exclude '*.so*' -w {dest_dir} {wheel}",
]

[tool.ruff.lint]
ignore = ["F811", "T001", "UP006", "UP007", "UP035", "UP045"]
