# This workflow will test a build on commit without publishing to PyPI

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Test Build Process

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-wheels:
    name: Test wheels (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
          - os: macos-26-intel
          - os: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"
          architecture: "x64"

      - name: Verify Python architecture
        run: |
          python -c "import platform, sys; print(sys.executable); print(platform.machine())"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

  build-sdist:
    name: Test source distribution
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"

      - name: Install build
        run: python -m pip install build

      - name: Build source distribution
        run: python -m build --sdist
